import { memo } from "react"; import { Label } from "@/components/ui/label"; import { Switch } from "@/components/ui/switch"; import { Button } from "@/components/ui/button"; import { Plus, Trash2 } from "lucide-react"; import { DebouncedInputV2 } from "@/components/admin/shared-v2/DebouncedInputV2"; import { DebouncedTextareaV2 } from "@/components/admin/shared-v2/DebouncedTextareaV2"; import { ImageUploadV2 } from "@/components/admin/shared-v2/ImageUploadV2"; import { SectionCTAEditorV2 } from "@/components/admin/shared-v2/SectionCTAEditorV2"; import type { V2SectionEditorProps } from "./types";
export const BenefitsEditorV2 = memo(({ draft, updateField, updateSection }: V2SectionEditorProps) => { const b = draft.benefits; const items = b?.items||[];
  return (<div className="rounded-3xl p-10 space-y-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold text-foreground">Benefícios</h2><div className="flex items-center space-x-2"><Switch checked={b?.enabled!==false} onCheckedChange={(c)=>updateField('benefits','enabled',c)} /><Label>Ativar</Label></div></div>
    <div className="bg-muted/20 rounded-2xl p-6 space-y-4"><Label className="text-foreground font-semibold text-lg">Título</Label><DebouncedInputV2 value={b?.title||''} onDebouncedChange={(v)=>updateField('benefits','title',v)} /></div>
    <div className="bg-muted/20 rounded-2xl p-6 space-y-4"><div className="flex items-center justify-between"><Label>Itens ({items.length})</Label><Button variant="outline" size="sm" onClick={()=>updateSection('benefits',{...b,items:[...items,{title:'',description:'',image:''}]})}><Plus className="h-4 w-4 mr-1"/>Adicionar</Button></div>
    {items.map((item,i)=>(<div key={i} className="bg-muted/20 rounded-2xl p-6 space-y-4"><div className="flex justify-between"><span className="text-sm text-muted-foreground">Benefício {i+1}</span><Button variant="ghost" size="sm" onClick={()=>updateSection('benefits',{...b,items:items.filter((_,j)=>j!==i)})} className="text-destructive"><Trash2 className="h-4 w-4"/></Button></div>
      <DebouncedInputV2 value={item.title||''} onDebouncedChange={(v)=>{const n=[...items];n[i]={...n[i],title:v};updateSection('benefits',{...b,items:n});}} placeholder="Título" />
      <DebouncedTextareaV2 value={item.description||''} onDebouncedChange={(v)=>{const n=[...items];n[i]={...n[i],description:v};updateSection('benefits',{...b,items:n});}} placeholder="Descrição" rows={2} />
      <ImageUploadV2 label="Imagem" value={item.image} onChange={(u)=>{const n=[...items];n[i]={...n[i],image:u};updateSection('benefits',{...b,items:n});}} /></div>))}</div>
    <SectionCTAEditorV2 sectionTitle="Benefícios" ctaData={b?.footerCta} onUpdate={(u)=>updateSection('benefits',{...b,footerCta:{...(b?.footerCta||{enabled:false,text:'',link:'',mobileHidden:false}),...u}})} /></div>);
}); BenefitsEditorV2.displayName='BenefitsEditorV2';
