import { memo } from "react"; import { Label } from "@/components/ui/label"; import { Switch } from "@/components/ui/switch"; import { DebouncedInputV2 } from "@/components/admin/shared-v2/DebouncedInputV2"; import { SectionCTAEditorV2 } from "@/components/admin/shared-v2/SectionCTAEditorV2"; import { Button } from "@/components/ui/button"; import { Plus, Trash2 } from "lucide-react"; import { ImageUploadV2 } from "@/components/admin/shared-v2/ImageUploadV2"; import type { V2SectionEditorProps } from "./types";
export const HowItWorksEditorV2 = memo(({ draft, updateField, updateSection }: V2SectionEditorProps) => { const s = draft.howItWorks; const steps = s?.steps||[];
  return (<div className="rounded-3xl p-10 space-y-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold text-foreground">Como Funciona</h2><div className="flex items-center space-x-2"><Switch checked={s?.enabled!==false} onCheckedChange={(c)=>updateField('howItWorks','enabled',c)} /><Label>Ativar</Label></div></div>
    <div className="bg-muted/20 rounded-2xl p-6 space-y-4"><DebouncedInputV2 value={s?.title||''} onDebouncedChange={(v)=>updateField('howItWorks','title',v)} placeholder="Título" /></div>
    <div className="bg-muted/20 rounded-2xl p-6 space-y-4"><div className="flex flex-wrap gap-6 justify-center"><ImageUploadV2 label="Desktop" value={s?.imageDesktop} onChange={(u)=>updateField('howItWorks','imageDesktop',u)} /><ImageUploadV2 label="Mobile" value={s?.imageMobile} onChange={(u)=>updateField('howItWorks','imageMobile',u)} /></div></div>
    <div className="bg-muted/20 rounded-2xl p-6 space-y-4"><div className="flex items-center justify-between"><Label>Passos ({steps.length})</Label><Button variant="outline" size="sm" onClick={()=>updateSection('howItWorks',{...s,steps:[...steps,'']})}><Plus className="h-4 w-4 mr-1"/>Add</Button></div>
    {steps.map((step,i)=>(<div key={i} className="flex items-center gap-3"><span className="text-sm text-muted-foreground w-6">{i+1}.</span><DebouncedInputV2 value={step||''} onDebouncedChange={(v)=>{const n=[...steps];n[i]=v;updateSection('howItWorks',{...s,steps:n});}} className="flex-1" /><Button variant="ghost" size="sm" onClick={()=>updateSection('howItWorks',{...s,steps:steps.filter((_,j)=>j!==i)})} className="text-destructive"><Trash2 className="h-4 w-4"/></Button></div>))}</div>
    <SectionCTAEditorV2 sectionTitle="Como Funciona" ctaData={s?.footerCta} onUpdate={(u)=>updateSection('howItWorks',{...s,footerCta:{...(s?.footerCta||{enabled:false,text:'',link:'',mobileHidden:false}),...u}})} /></div>);
}); HowItWorksEditorV2.displayName='HowItWorksEditorV2';
