// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dznxtnwaohdjfmnyjkjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6bnh0bndhb2hkamZtbnlqa2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MzYxNTIsImV4cCI6MjA4NTExMjE1Mn0.QPvSMILeApsw-YsRo3xW7MzCg33x_FfptdgW7SwI178";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});